### ISSUE TITLE
Empty card and error in log "unterminated quoted string"

### ISSUE THREAD

**Issue by guidokieboom** [aex351/home-assistant-neerslag-card#12]
Great frontend! Installed card via HACS and added to configuration.yaml per the readme instructions. Unfortunately card remains empty (data are pulled in). Could you help me to troubleshoot / resolve? Thanks!

<img width="408" alt="Screenshot 2021-04-03 at 19 59 17" src="https://user-images.githubusercontent.com/65387179/113487452-7bfcf200-94b8-11eb-940c-c80e8a97e9f5.png">

<img width="801" alt="Screenshot 2021-04-03 at 20 00 17" src="https://user-images.githubusercontent.com/65387179/113487418-540d8e80-94b8-11eb-8064-8718a34eadbe.png">

<img width="376" alt="Screenshot 2021-04-03 at 19 59 28" src="https://user-images.githubusercontent.com/65387179/113487411-4d7f1700-94b8-11eb-90ff-376a6fb93367.png">

<img width="1118" alt="Screenshot 2021-04-03 at 20 05 15" src="https://user-images.githubusercontent.com/65387179/113487493-ab136380-94b8-11eb-9a85-3e72bdd549a2.png">

**Comment by guidokieboom** [comment]
After approx. 15hrs the graph appeared. No action taken. Suggest to include this in the readme.

**Comment by aex351** [comment]
Thanks for the feedback. I will have a look to see if there can be a message of some sorts on the card to display the sensor status.
