### ISSUE TITLE
Warning for undefined variable in template

### ISSUE THREAD

**Issue by dynasticorpheus** [aex351/home-assistant-neerslag-card#13]
As per [2021.4](https://www.home-assistant.io/blog/2021/04/07/release-20214/#warnings-for-undefined-variables-in-templates) release a warning is shown which can be solved by setting default value for template sensor as per below.

from:
`value_template: 'last_changed: {{states.sensor.neerslag_buienalarm_regen_data.last_changed}}'`

to:
`value_template: 'last_changed: {{states.sensor.neerslag_buienalarm_regen_data.last_changed | default(now())}}'
`

**Comment by aex351** [comment]
Thanks @dynasticorpheus. I have updated the readme file and created a new release.
