### ISSUE TITLE
card not showing data any more

### ISSUE THREAD

**Issue by canedje** [aex351/home-assistant-neerslag-card#14]
After update to HA 2021.4.1 Neerslag-card is not showing data anymore.
Sensors are still there
![image](https://user-images.githubusercontent.com/23150947/114197065-4772b580-9952-11eb-892b-146c11a025f5.png)
![image](https://user-images.githubusercontent.com/23150947/114197140-56f1fe80-9952-11eb-8184-9d197ceb251d.png)
![image](https://user-images.githubusercontent.com/23150947/114197215-6709de00-9952-11eb-9f19-e01417e2b2f7.png)

ha log gives error 500 at buienradar sensor

**Comment by littlbee** [comment]
Same, card is not working anymore in 2021.4.2, although both sensor.buienalarm_regen_data and sensor.buienradar_regen_data do have data

**Comment by canedje** [comment]
I did change both sensors.
Now it is working

**Comment by aex351** [comment]
The custom sensor names have been changed a couple of updates (releases) back. This was done to align the Neerslag Card with the Neerslag App (https://github.com/aex351/home-assistant-neerslag-app). See also: https://github.com/aex351/home-assistant-neerslag-card/releases/tag/2021.04.05.0.

The Neerslag App is not part of the default HACS repository yet. However, I do recommend to migrate from the Neerslag Card to the Neerslag App. You can add the Neerslag App as a custom repository.

**Comment by canedje** [comment]
I migrated to neerslag app. Working fine.
I now can remove the HACS neerslag card?

**Comment by littlbee** [comment]
Perfect @aex351 , renaming the sensors in the configuration.yaml did indeed solve the issue.

**Comment by aex351** [comment]
> I migrated to neerslag app. Working fine.
> I now can remove the HACS neerslag card?

Yes, if you have migrated you should remove the standalone Neerslag Card + custom sensors.
