### ISSUE TITLE
Unable to parse output as JSON

### ISSUE THREAD

**Issue by AndyVRD** [aex351/home-assistant-neerslag-card#16]
Hi,

Just installed and works fine but always trows this error multiple times in a hour. I only changed the nl to be in the url, but I think that will not cause this error?

Logger: homeassistant.components.command_line.sensor
Source: components/command_line/sensor.py:120 
Integration: command_line

**Comment by aex351** [comment]
Changing the extension of the URL should not cause any errors for the custom sensors. However, I have only used and tested these external services with the `.nl` extension. 

The warning/error messages you are experiencing are caused when these external services are not responding or responding fast enough. This causes the command line integration (used by the custom sensors) to throw a warning/error message. The only thing you can do is to increase the timeout value. 

So the error/warning messages are not part of the actual Neerslag Card, which is purely a front-end.
