### ISSUE TITLE
Data flows in, empty chart

### ISSUE THREAD

**Issue by plat1231** [aex351/home-assistant-neerslag-card#17]
Love this frontend! It used to work perfectly for me, however since a week or so the graph doesn't show any info.
Data is still being collect.
![no_graph](https://user-images.githubusercontent.com/72915670/114666519-a5aaea00-9cfe-11eb-9a63-3230b34cc3bd.png)
I don't see any related errors in the log (at least, not with my knowledge).
I first expected a device/browser issue, but that was ruled out as all no devices show the graph.

Any support or thoughts is appreciated. Thanks in advance.

**Comment by aex351** [comment]
In an earlier update the custom sensor names got changed. They are now prefixed with `neerslag_`. See also the readme file. Updating the custom sensor names in `configuration.yaml` should fix the issue.

This change was done to align the Neerslag Card with the Neerslag App. The Neerslag App is not yet part of the default HACS repository, however I would still recommend to migrate to the Neerslag App. You can do this by adding the Neerslag App as a custom repository in HACS.

**Comment by plat1231** [comment]
Thanks a ton! That worked. Well, to be honest. I've installed the update (2021.02.27.2, is the version correct?). 🙏
