### ISSUE TITLE
No mark for light, moderate and heavy rainfall

### ISSUE THREAD

**Issue by BartEngelen** [aex351/home-assistant-neerslag-card#3]
Hello,
I do not see the marks for light, moderate and heavy rainfall.
![image](https://user-images.githubusercontent.com/17978789/111137927-a88bb100-857f-11eb-9b9d-7b9f6a5a2780.png)
Thanks for yout help.
Regards,
Bart

**Comment by BartEngelen** [comment]
Hello,
I see the marks now.
Problem solved !
Thanks

**Comment by aex351** [comment]
I see you opened and closed this issue already. The issue you describe actually is a minor bug that sometimes can occur. I do not know the root cause. A simple page refresh fixes the issue.
