### ISSUE TITLE
Neerslag card not found

### ISSUE THREAD

**Issue by xfader2018** [aex351/home-assistant-neerslag-card#30]
Installed **Neerslag App** following procedures.
Also installed integration and entities are found, however when I want to add the card for the graph then the card it's not found.
Even adding it in yaml says card not found.

HA: 2021.12.5

<img width="995" alt="Screen Shot 2021-12-24 at 12 32 11" src="https://user-images.githubusercontent.com/42482961/147349458-431c2e5e-3ed4-4054-8470-7db25c060f5a.png">

**Comment by aex351** [comment]
You will need to restart Home Assistant and make sure the browser cache is cleared. If you would try this in a private browser window and have installed the Neerslag App correctly, you should see the card.
