### ISSUE TITLE
Mobile app

### ISSUE THREAD

**Issue by FilipRoels** [aex351/home-assistant-neerslag-card#33]
Hi,

I'm new in HA so i'm sorry if this is a stupid question. I'm having problems with the Neerslag Card on the mobile app. I get the error "Custom element doesn't exist: neerslag-card.".

Did I do something wrong?

Best
Filip
Belgium

**Comment by KobeNuyts** [comment]
I have the same problem.

(I'm also from Belgium) maybe it's links to that.

**Comment by aex351** [comment]
This can occur when there is a caching issue. By cleaning the app cache and/or restarting the app the problem should be resolved.  It is not related to a specific country (e.g. Belgium).
