### ISSUE TITLE
Card stopt working

### ISSUE THREAD

**Issue by horve000** [aex351/home-assistant-neerslag-card#35]
Today the 'custom:neerslag-crad' stopt working after using it for several months i did serveral reïnstalls but nothing helped. My buienradar sensor seems to be working normal. 
 
![Schermafbeelding_20221028_151429](https://user-images.githubusercontent.com/6498608/198602890-dd01c299-36c2-4e9e-a8cf-86bd745cb56c.png)

**Comment by GertJanArts** [comment]
Same here

> Today the 'custom:neerslag-crad' stopt working after using it for several months i did serveral reïnstalls but nothing helped. My buienradar sensor seems to be working normal.
> 
> ![Schermafbeelding_20221028_151429](https://user-images.githubusercontent.com/6498608/198602890-dd01c299-36c2-4e9e-a8cf-86bd745cb56c.png)

Same here

**Comment by horve000** [comment]
It started working again.
