### ISSUE TITLE
Nothing displayed

### ISSUE THREAD

**Issue by geidorei** [aex351/home-assistant-neerslag-card#39]
All setup via HACS, no issue there.

But nothing is showing. I know its states that if there is no data it will be blank.... but

Alarm is just showing an empty graph, and regan is blank.

Also, can we change the x/y axis legends to English?

Many thanks?

**Comment by aex351** [comment]
If the graph is empty, it typically means there is no sensor data. Have a look at the documentation for setting up the custom sensors. 

The graph will be displayed in English if your browser/system settings are set to that.
