### ISSUE TITLE
Buienradar data field empty

### ISSUE THREAD

**Issue by haaino** [aex351/home-assistant-neerslag-card#43]
Dear readers,

I noticed that since 23-11-2023 the data field of the neerslag_buienradar_regen_data is empty. 
The last changed is updated. 

Does anybody else have this issue as well?

**Comment by aex351** [comment]
The Buienradar api is broken. Currently the service is returning an HTTP 500 error. The `neerslag-card`  is correctly showing the message that there is no sensor data available.

This means it has got nothing to do with Home Assisant or the `neerslag-card` itself. 

The Buienradar team will need to fix the api or for the `neerslag-card` we need to see what alternative options are available for using Buienradar data.

**Comment by haaino** [comment]
It started working again. It seems the supplier fixed the issue 😊

**Comment by aex351** [comment]
The Buienradar api is working again. No change has been made for the `neerslag-card`.
