### ISSUE TITLE
Timeout for command: python3

### ISSUE THREAD

**Issue by sanderlv** [aex351/home-assistant-neerslag-card#8]
Logger: homeassistant.components.command_line
Source: components/command_line/__init__.py:43
Integration: command_line (documentation, issues)
First occurred: 9:41:59 AM (1 occurrences)
Last logged: 9:41:59 AM

Timeout for command: python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=55.0&lon=4.4&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}'; print(data);"

**Comment by aex351** [comment]
No it is not an issue with the card. It happens when the service doesn't respond or responds fast enough.

**Comment by sanderlv** [comment]
Thanks for the reply... I also do not get a feed:
![image](https://user-images.githubusercontent.com/16528916/111760054-9327c700-889e-11eb-8605-fbccc7160e87.png)

**Comment by aex351** [comment]
That currently happens when there is no or invalid rain data.

See the following https://github.com/aex351/home-assistant-neerslag-card/issues/2#issuecomment-799471703.

**Comment by sanderlv** [comment]
I kept getting errors, it never filled with data. But I managed to resolve the issue :-)

![image](https://user-images.githubusercontent.com/16528916/112440122-39b21300-8d4a-11eb-844e-657c3b1957ad.png)

Maybe later when I have more patience I will try again. Thanks for the support an keep up 👍

**Comment by aex351** [comment]
I can imagine it can be a bit challenging to set-up those custom sensors. 

Currently I am working on creating a Neerslag Integration. This will be an all-in-one package. Which includes Buienalarm and Buienradar sensor and the Neerslag Card. So it will be pretty much plug-and-play. So no more need to set-up and configure the custom sensors yourself in `configuration.yaml`.
